### ISSUE TITLE
Make overflow behaviour changeable & document default

### ISSUE THREAD

**Issue by marcellussiegburg** [marcellussiegburg/call-alloy#2]
- Make the overflow behaviour changeable (see https://github.com/marcellussiegburg/call-alloy/blob/51af86c12d58d8e7d7b581e242b30642663bf3b9/bin/RunAlloy.java#L34)
- document the default behaviour

**Comment by jvoigtlaender** [comment]
I guess that would simply be a `Bool`-typed function argument to `existsInstance` and `getInstances`?

**Comment by marcellussiegburg** [comment]
Yes, I guess breaking the API (and increasing a major version) by introducing a new parameter is the right move here.

**Comment by jvoigtlaender** [comment]
An alternative of course would be to keep the current `existsInstance` and `getInstances` functions, and introduce new versions `existsInstanceWithConfig`/`getInstancesWithConfig` that get this extra parameter, and later also potentially get further extra parameters (maybe in the form of a config record) like start seed or whatever.

Then the "default" versions `existsIntance` and `getInstances` could remain stable in the API for longer or maybe forever.
