### ISSUE TITLE
Document what things "look like"

### ISSUE THREAD

**Issue by jvoigtlaender** [marcellussiegburg/call-alloy#5]
I think what I would need as part of the public documentation:
- an example of a short Alloy specification
- how one of the `AlloyInstance`s returned from a `getInstances` call for said specification could look like, as a (pretty-printed) `Map Signature (Entry Map Set)` value, at least partially given, with at least for one of the stored `Entry Map Set` values also shown what the `annotation` would be and at least sketched how the `relation` looks as a `Map String (Relation Set)`
- relevant `scoped`- and `unscoped`-calls for creating `Signature` values for the above instance
- examples of relevant `getSingle`, `getDouble`, `getTriple` calls along with their results for the above instance; so the example specification would have to be such that all three cases occur
- the possible cases/accessors for `Object`s

**Comment by marcellussiegburg** [comment]
Everything mentioned is covered by the README already.

@jvoigtlaender Feel free to reopen if you think there is still something missing
